"
I store metadata for this package. These meta data are used by other tools such as the SmalllintManifestChecker and the critics Browser
"
Class {
	#name : #ManifestINGCOMBIUICHOFER,
	#superclass : #PackageManifest,
	#category : #'ING2-COMBI19-UI-CHOFER-Manifest'
}

{ #category : #'code-critics' }
ManifestINGCOMBIUICHOFER class >> ruleGRGuardClauseRuleV1FalsePositive [
	^ #(#(#(#RGMethodDefinition #(#VenderBoletoView #confirmarVenta #false)) #'2021-07-11T21:17:19.394543-03:00') )
]
